kind: Deployment
apiVersion: apps/v1
metadata:
  name: obscure-truth-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: obscure-truth-ui
  template:
    metadata:
      labels:
        app: obscure-truth-ui
    spec:
      containers:
      - name: obscure-truth-ui
        image: martinhodges/obscure-truth
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: obscure-truth-ui-lb
  labels:
    app: obscure-truth-ui-lb
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  selector:
    app: obscure-truth-ui

